import { MethodologyPhaseDefinition, MethodologyPhaseId, MethodologyManifest } from './methodology.types.js';

export class MethodologyRegistry {
  private static readonly phases: MethodologyPhaseDefinition[] = [
    {
      id: '00-loader',
      numericCode: '00',
      name: 'Framework Loader & Environment Discovery',
      shortName: 'Loader & Discovery',
      description: 'Discovers local system capabilities, validates project directory structure, and initializes repository integrity.',
      objective: 'Map system environment, CLI tools, MCP capabilities, and scan client assets.',
      agentPromptFile: '00-framework-loader.md',
      templateFile: 'discovery-template.md',
      inputs: ['client-briefing-folder'],
      outputs: ['environment-discovery.md', 'project-index.json'],
      outputArtifacts: ['00-loader/environment-discovery.md', 'project-index.json', 'PROJECT_ANALYSIS.md'],
      dependencies: [],
      approvalRequired: false,
      retryPolicy: { maxAttempts: 3, backoffMs: 500, timeoutMs: 30000 },
      failurePolicy: 'halt',
    },
    {
      id: '01-discovery',
      numericCode: '01',
      name: 'Business & Project Discovery',
      shortName: 'Business Discovery',
      description: 'Investigates client business mechanics, target audience ICP, primary commercial barriers, and competitor whitespace.',
      objective: 'Establish verified commercial facts and map ICP psychological pain points.',
      agentPromptFile: '01-discovery-agent.md',
      templateFile: 'discovery-template.md',
      inputs: ['environment-discovery.md', 'project-index.json'],
      outputs: ['discovery.md'],
      outputArtifacts: ['01-discovery/discovery.md'],
      dependencies: ['00-loader'],
      approvalRequired: false,
      retryPolicy: { maxAttempts: 3, backoffMs: 500, timeoutMs: 30000 },
      failurePolicy: 'halt',
    },
    {
      id: '02-brand-strategy',
      numericCode: '02',
      name: 'Brand Strategy & Voice Positioning',
      shortName: 'Brand Strategy',
      description: 'Establishes brand archetype, Golden Circle, visual personality, and verbal positioning matrix.',
      objective: 'Formulate indestructible verbal positioning and archetype routing.',
      agentPromptFile: '02-brand-strategy-agent.md',
      templateFile: 'brand-strategy-template.md',
      inputs: ['01-discovery/discovery.md'],
      outputs: ['brand-strategy.md'],
      outputArtifacts: ['02-brand-strategy/brand-strategy.md'],
      dependencies: ['01-discovery'],
      approvalRequired: false,
      retryPolicy: { maxAttempts: 3, backoffMs: 500, timeoutMs: 30000 },
      failurePolicy: 'halt',
    },
    {
      id: '03-design-system',
      numericCode: '03',
      name: 'Semantic Design Tokens & System',
      shortName: 'Design System',
      description: 'Synthesizes mathematical HSL 60-30-10 color tokens, typographic scale ratio, and layout grid variables.',
      objective: 'Enforce mathematical design token constraints and WCAG 2.2 contrast compliance.',
      agentPromptFile: '03-design-system-agent.md',
      templateFile: 'design-system-template.md',
      inputs: ['02-brand-strategy/brand-strategy.md'],
      outputs: ['design-system.md'],
      outputArtifacts: ['03-design-system/design-system.md'],
      dependencies: ['02-brand-strategy'],
      approvalRequired: false,
      retryPolicy: { maxAttempts: 3, backoffMs: 500, timeoutMs: 30000 },
      failurePolicy: 'halt',
    },
    {
      id: '04-copywriting',
      numericCode: '04',
      name: 'Master Copywriting (AIDA & Anti-AI)',
      shortName: 'Master Copywriting',
      description: 'Crafts human, persuasive AIDA conversion narrative, eliminating AI clichés and gerund inflation.',
      objective: 'Write Hero H1 value proposition, section headlines, and CTA copy.',
      agentPromptFile: '04-copywriting-agent.md',
      templateFile: 'copywriting-template.md',
      inputs: ['02-brand-strategy/brand-strategy.md', '03-design-system/design-system.md'],
      outputs: ['copywriting.md'],
      outputArtifacts: ['04-copywriting/copywriting.md'],
      dependencies: ['03-design-system'],
      approvalRequired: false,
      retryPolicy: { maxAttempts: 3, backoffMs: 500, timeoutMs: 30000 },
      failurePolicy: 'halt',
    },
    {
      id: '05-creative-direction',
      numericCode: '05',
      name: 'Visual Creative Direction (DFII >= 10)',
      shortName: 'Creative Direction',
      description: 'Defines 3D lighting vignette, visual concept, depth layers, and calculates DFII originality score.',
      objective: 'Establish cinematic visual direction with DFII score >= 10.',
      agentPromptFile: '05-creative-direction-agent.md',
      templateFile: 'creative-direction-template.md',
      inputs: ['04-copywriting/copywriting.md'],
      outputs: ['creative-direction.md', 'creative-dna.json', 'decision-logs.json'],
      outputArtifacts: ['05-creative-direction/creative-direction.md', 'design/creative-dna.json', 'design/decision-logs.json'],
      dependencies: ['04-copywriting'],
      approvalRequired: false,
      retryPolicy: { maxAttempts: 3, backoffMs: 500, timeoutMs: 30000 },
      failurePolicy: 'halt',
    },
    {
      id: '06-experience-design',
      numericCode: '06',
      name: 'Experience Design & User Journey Mapping',
      shortName: 'Experience Design',
      description: 'Scripts scroll transitions, card stacking, scene pacing, and interactive cursor physics.',
      objective: 'Design physical scroll choreography and interactive scene transitions.',
      agentPromptFile: '06-experience-design-agent.md',
      templateFile: 'experience-design-template.md',
      inputs: ['05-creative-direction/creative-direction.md'],
      outputs: ['experience-design.md'],
      outputArtifacts: ['06-experience-design/experience-design.md'],
      dependencies: ['05-creative-direction'],
      approvalRequired: false,
      retryPolicy: { maxAttempts: 3, backoffMs: 500, timeoutMs: 30000 },
      failurePolicy: 'halt',
    },
    {
      id: '07-ui-architecture',
      numericCode: '07',
      name: 'UI Architecture & Bento Grid System',
      shortName: 'UI Architecture',
      description: 'Engineers responsive 12-column Bento Grid layout, column spans, and mobile-first container boundaries.',
      objective: 'Produce structural wireframe specification and Bento Grid layout.',
      agentPromptFile: '07-ui-architecture-agent.md',
      templateFile: 'ui-architecture-template.md',
      checklistFile: 'design-gate.md',
      inputs: ['06-experience-design/experience-design.md'],
      outputs: ['ui-architecture.md'],
      outputArtifacts: ['07-ui-architecture/ui-architecture.md'],
      dependencies: ['06-experience-design'],
      approvalRequired: false,
      retryPolicy: { maxAttempts: 3, backoffMs: 500, timeoutMs: 30000 },
      failurePolicy: 'halt',
    },
    {
      id: '07.1-cinematic-experience',
      numericCode: '07.1',
      name: 'Cinematic Scroll Motion & GSAP Physics',
      shortName: 'Cinematic Motion',
      description: 'Configures Lenis smooth scroll, GSAP ScrollTrigger timeline animations, and GPU acceleration.',
      objective: 'Ensure 60fps+ fluid scroll physics and cinematic animation timing.',
      agentPromptFile: '07.1-cinematic-experience-agent.md',
      templateFile: 'experience-design-template.md',
      inputs: ['07-ui-architecture/ui-architecture.md'],
      outputs: ['cinematic-experience.md'],
      outputArtifacts: ['07.1-cinematic-experience/cinematic-experience.md'],
      dependencies: ['07-ui-architecture'],
      approvalRequired: false,
      retryPolicy: { maxAttempts: 3, backoffMs: 500, timeoutMs: 30000 },
      failurePolicy: 'halt',
    },
    {
      id: '08-implementation',
      numericCode: '08',
      name: 'Production Front-End Implementation',
      shortName: 'Implementation',
      description: 'Compiles clean HTML5, CSS3 native tokens, JS motion scripts, sitemap, and robots.txt.',
      objective: 'Generate production-ready code in landing/ directory.',
      agentPromptFile: '08-implementation-agent.md',
      templateFile: 'ui-architecture-template.md',
      checklistFile: 'development-gate.md',
      inputs: ['07.1-cinematic-experience/cinematic-experience.md'],
      outputs: ['index.html', 'styles.css', 'app.js', 'implementation-report.md'],
      outputArtifacts: ['landing/index.html', 'landing/styles.css', 'landing/app.js', 'reports/build-report.md'],
      dependencies: ['07.1-cinematic-experience'],
      approvalRequired: false,
      retryPolicy: { maxAttempts: 3, backoffMs: 500, timeoutMs: 30000 },
      failurePolicy: 'halt',
    },
    {
      id: '08.1-final-audit',
      numericCode: '08.1',
      name: 'Final Audit & Quality Gates',
      shortName: 'Final Audit',
      description: 'Runs 9 modular auditors, self-healing loop, and validates 7 Quality Gates.',
      objective: 'Pass 100% Quality Gates (Performance >= 90, SEO >= 95, WCAG >= 95).',
      agentPromptFile: '08.1-final-audit-agent.md',
      templateFile: 'audit-template.md',
      checklistFile: 'quality-gate.md',
      inputs: ['landing/index.html', 'landing/styles.css'],
      outputs: ['FINAL_AUDIT.md', 'EXECUTION_REPORT.md'],
      outputArtifacts: ['reports/FINAL_AUDIT.md', 'reports/EXECUTION_REPORT.md'],
      dependencies: ['08-implementation'],
      approvalRequired: true,
      retryPolicy: { maxAttempts: 3, backoffMs: 500, timeoutMs: 30000 },
      failurePolicy: 'halt',
    },
    {
      id: '09-publication',
      numericCode: '09',
      name: 'Production Deployment & Publication',
      shortName: 'Publication',
      description: 'Prepares production HTTPS deployment package, verifies sitemap/robots, and emits publication report.',
      objective: 'Emit final publication report and transition project state to READY_FOR_PUBLICATION.',
      agentPromptFile: '09-publication-agent.md',
      templateFile: 'publication-template.md',
      checklistFile: 'publication-gate.md',
      inputs: ['reports/FINAL_AUDIT.md'],
      outputs: ['publication-report.md'],
      outputArtifacts: ['reports/publication-report.md'],
      dependencies: ['08.1-final-audit'],
      approvalRequired: true,
      retryPolicy: { maxAttempts: 3, backoffMs: 500, timeoutMs: 30000 },
      failurePolicy: 'halt',
    },
  ];

  public static getOfficialPhases(): MethodologyPhaseDefinition[] {
    return [...this.phases];
  }

  public static getPhaseById(id: MethodologyPhaseId): MethodologyPhaseDefinition | undefined {
    return this.phases.find((p) => p.id === id);
  }

  public static getPhaseByNumericCode(code: string): MethodologyPhaseDefinition | undefined {
    return this.phases.find((p) => p.numericCode === code);
  }

  public static getManifest(): MethodologyManifest {
    return {
      name: 'KDL Landing Framework Methodology',
      version: '1.0.0',
      totalOfficialPhases: this.phases.length,
      phases: this.getOfficialPhases(),
    };
  }
}
