import fs from 'fs';
import path from 'path';
import { ProjectIndex, ValidationResult } from '../types/bootstrap.types.js';

export class MarkdownGenerator {
  public static generateAnalysis(index: ProjectIndex, validation: ValidationResult): string {
    const lines = [
      `# PROJECT ANALYSIS — ${index.projectName}`,
      ``,
      `> **Generated by KDL Bootstrap Engine v1.0.0**`,
      `> **Date:** ${new Date().toISOString()}`,
      ``,
      `## 1. Executive Summary`,
      `- **Project Name:** ${index.projectName}`,
      `- **Validation Score:** ${validation.score}/100 (${validation.passed ? 'PASSED' : 'NEEDS_ATTENTION'})`,
      `- **Total Client Files Analyzed:** ${index.totalFiles}`,
      `- **Total Storage Size:** ${(index.totalSizeBytes / (1024 * 1024)).toFixed(2)} MB`,
      ``,
      `## 2. Issues & Audit Findings`,
    ];

    if (validation.issues.length === 0) {
      lines.push(`- ✅ Zero critical issues or warnings detected in client files.`);
    } else {
      for (const issue of validation.issues) {
        lines.push(`- **[${issue.severity}]** ${issue.message}`);
        lines.push(`  - *Action:* ${issue.recommendation}`);
      }
    }

    return lines.join('\n');
  }

  public static generateStructure(index: ProjectIndex, createdDirs: string[]): string {
    const lines = [
      `# PROJECT STRUCTURE — ${index.projectName}`,
      ``,
      `## Standard KDL Directories (${createdDirs.length} created)`,
      ...createdDirs.map((d) => `- \`./${d}/\``),
      ``,
      `## File Inventory (${index.totalFiles} files)`,
    ];

    for (const file of index.files) {
      lines.push(`- \`${file.relativePath}\` (${file.category}, ${(file.sizeBytes / 1024).toFixed(1)} KB, SHA-256: ${file.sha256.substring(0, 8)}...)`);
    }

    return lines.join('\n');
  }

  public static generateProfile(index: ProjectIndex): string {
    const logos = index.files.filter((f) => f.category === 'Logo' || f.category === 'Vector');
    const briefings = index.files.filter((f) => f.category === 'Briefing');
    const images = index.files.filter((f) => f.category === 'Image');

    return [
      `# CLIENT PROFILE — ${index.projectName}`,
      ``,
      `## Brand Assets Summary`,
      `- **Logos Detected:** ${logos.length} (${logos.map((l) => l.filename).join(', ') || 'None'})`,
      `- **Briefing Documents:** ${briefings.length} (${briefings.map((b) => b.filename).join(', ') || 'None'})`,
      `- **Brand Images:** ${images.length}`,
    ].join('\n');
  }

  public static generatePlan(validation: ValidationResult): string {
    return [
      `# EXECUTION PLAN — KDL METHODOLOGY`,
      ``,
      `## Phase Readiness`,
      `- **Phase 00 (Loader):** COMPLETED`,
      `- **Phase 01 (Discovery):** READY`,
      `- **Validation Gate:** ${validation.passed ? 'PASSED (Ready for AI Engine)' : 'BLOCKED (Fix critical issues first)'}`,
    ].join('\n');
  }

  public static writeAllMarkdownDocs(
    projectPath: string,
    index: ProjectIndex,
    validation: ValidationResult,
    createdDirs: string[],
  ): Record<string, string> {
    const analysis = this.generateAnalysis(index, validation);
    const structure = this.generateStructure(index, createdDirs);
    const profile = this.generateProfile(index);
    const plan = this.generatePlan(validation);

    const paths = {
      analysisPath: path.join(projectPath, 'PROJECT_ANALYSIS.md'),
      structurePath: path.join(projectPath, 'PROJECT_STRUCTURE.md'),
      profilePath: path.join(projectPath, 'CLIENT_PROFILE.md'),
      planPath: path.join(projectPath, 'EXECUTION_PLAN.md'),
    };

    fs.writeFileSync(paths.analysisPath, analysis, 'utf-8');
    fs.writeFileSync(paths.structurePath, structure, 'utf-8');
    fs.writeFileSync(paths.profilePath, profile, 'utf-8');
    fs.writeFileSync(paths.planPath, plan, 'utf-8');

    return paths;
  }
}
