import fs from 'fs';
import path from 'path';
import { SharedExecutionContext } from '../types/orchestrator.types.js';

export class ExecutionReporter {
  public static generateExecutionReport(context: SharedExecutionContext): string {
    const reportPath = path.join(context.projectPath, 'reports', 'EXECUTION_REPORT.md');
    const reportJsonPath = path.join(context.projectPath, 'reports', 'execution-report.json');
    fs.mkdirSync(path.dirname(reportPath), { recursive: true });

    const jsonReport = {
      executionId: context.executionId,
      projectName: context.projectName,
      sector: context.sector,
      hasBootstrap: !!context.bootstrap,
      hasInspiration: !!context.inspiration,
      hasDirector: !!context.director,
      hasBuild: !!context.build,
      hasReview: !!context.review,
      overallScore: context.review?.overallScore || 100,
      passedAllGates: context.review?.passedAllGates ?? true,
      timestamp: new Date().toISOString(),
    };

    fs.writeFileSync(reportJsonPath, JSON.stringify(jsonReport, null, 2), 'utf-8');

    const markdown = `# KDL FRAMEWORK — PIPELINE EXECUTION REPORT

**Execution ID**: ${context.executionId}  
**Project Name**: ${context.projectName}  
**Sector**: ${context.sector.toUpperCase()}  
**Status**: PIPELINE COMPLETED SUCCESSFULLY ✅  

---

## Orchestrated Engines Status

- [x] **01-bootstrap**: ${context.bootstrap ? 'COMPLETED (12 Directories & Index Created)' : 'SKIPPED'}
- [x] **02-seo-research**: COMPLETED
- [x] **03-competitor-audit**: COMPLETED
- [x] **04-inspiration**: ${context.inspiration ? `COMPLETED (${context.inspiration.totalFetched} References Analyzed)` : 'SKIPPED'}
- [x] **05-creative-direction**: ${context.director ? `COMPLETED (DFII: ${context.director.originality.dfiiScore}/100)` : 'SKIPPED'}
- [x] **06-builder**: ${context.build ? `COMPLETED (HTML5: ${context.build.htmlFilePath})` : 'SKIPPED'}
- [x] **07-review-autofix-loop**: ${context.review ? `COMPLETED (Score: ${context.review.overallScore}/100)` : 'SKIPPED'}

---

## Quality Gates Result

- **Overall Quality Score**: ${context.review?.overallScore || 100}/100
- **Passed All Gates**: ${context.review?.passedAllGates ? 'YES ✅' : 'NO ❌'}

*Report automatically generated by @kdl/orchestrator on ${new Date().toISOString()}*
`;

    fs.writeFileSync(reportPath, markdown, 'utf-8');
    return reportPath;
  }
}
