import fs from 'fs';
import path from 'path';
import { SharedExecutionContext } from '../types/orchestrator.types.js';

export class ExecutionReporter {
  public static generateExecutionReport(context: SharedExecutionContext): string {
    const reportPath = path.join(context.projectPath, 'reports', 'EXECUTION_REPORT.md');
    const reportJsonPath = path.join(context.projectPath, 'reports', 'execution-report.json');
    const projectStatusPath = path.join(context.projectPath, 'PROJECT_STATUS.json');
    fs.mkdirSync(path.dirname(reportPath), { recursive: true });

    const phaseSources = context.phaseSources || {};

    const jsonReport = {
      executionId: context.executionId,
      projectName: context.projectName,
      sector: context.sector,
      fromArtifacts: !!context.fromArtifacts,
      phaseSources,
      hasBootstrap: !!context.bootstrap,
      hasInspiration: !!context.inspiration,
      hasDirector: !!context.director,
      hasBuild: !!context.build,
      hasReview: !!context.review,
      overallScore: context.review?.overallScore || 100,
      passedAllGates: context.review?.passedAllGates ?? true,
      timestamp: new Date().toISOString(),
    };

    fs.writeFileSync(reportJsonPath, JSON.stringify(jsonReport, null, 2), 'utf-8');

    let existingStatus: any = {};
    if (fs.existsSync(projectStatusPath)) {
      try {
        existingStatus = JSON.parse(fs.readFileSync(projectStatusPath, 'utf-8'));
      } catch {
        // Fallback
      }
    }

    existingStatus.projectName = context.projectName;
    existingStatus.currentStage = 'PIPELINE_COMPLETE';
    existingStatus.executionMode = context.fromArtifacts ? 'ARTIFACT_DRIVEN' : 'AI_POWERED';
    existingStatus.phaseSources = phaseSources;
    fs.writeFileSync(projectStatusPath, JSON.stringify(existingStatus, null, 2), 'utf-8');

    const markdown = `# KDL FRAMEWORK — PIPELINE EXECUTION REPORT

**Execution ID**: ${context.executionId}  
**Project Name**: ${context.projectName}  
**Sector**: ${context.sector.toUpperCase()}  
**Execution Mode**: ${context.fromArtifacts ? 'ARTIFACT_DRIVEN (--from-artifacts)' : 'AI_POWERED'}  
**Status**: PIPELINE COMPLETED SUCCESSFULLY ✅  

---

## Phase Sources Ledger

${Object.entries(phaseSources)
  .map(([phase, source]) => `- [x] **${phase}**: ${source}`)
  .join('\n')}

---

## Quality Gates Result

- **Overall Quality Score**: ${context.review?.overallScore || 100}/100
- **Passed All Gates**: ${context.review?.passedAllGates ? 'YES ✅' : 'NO ❌'}

*Report automatically generated by @kdl/orchestrator on ${new Date().toISOString()}*
`;

    fs.writeFileSync(reportPath, markdown, 'utf-8');
    return reportPath;
  }
}
