import fs from 'fs';
import path from 'path';
import { ReviewResult } from '../types/reviewer.types.js';

export class FinalAuditReporter {
  public static generateReport(projectPath: string, reviewResult: ReviewResult): string {
    const reportPath = path.join(projectPath, 'reports', 'FINAL_AUDIT.md');
    fs.mkdirSync(path.dirname(reportPath), { recursive: true });

    const markdown = `# KDL FRAMEWORK — AUTONOMOUS FINAL AUDIT REPORT

**Project Name**: ${reviewResult.projectName}  
**Overall Quality Score**: ${reviewResult.overallScore}/100  
**Iterations Completed**: ${reviewResult.iterationCount}  
**Auto-Fixes Applied**: ${reviewResult.totalAutoFixesApplied}  
**Status**: ${reviewResult.passedAllGates ? 'APPROVED FOR PRODUCTION ✅' : 'WARNINGS / REJECTED ❌'}

---

## Mandatory Quality Gates Checklist

${reviewResult.qualityGates
  .map((g) => `- [${g.passed ? 'x' : ' '}] **${g.name}**: ${g.score}/100 (Min Required: ${g.minRequiredScore}) — ${g.passed ? 'PASSED' : 'FAILED'}`)
  .join('\n')}

---

## Modular Auditors Breakdown

${reviewResult.auditorResults
  .map(
    (a) => `### ${a.auditorName} — Score: ${a.score}/100
Issues Identified: ${a.issues.length}
${a.issues.map((i) => `  - [${i.severity.toUpperCase()}] ${i.message} (Fix: ${i.suggestion})`).join('\n')}
`
  )
  .join('\n')}

---

*Report automatically generated by @kdl/reviewer on ${new Date().toISOString()}*
`;

    fs.writeFileSync(reportPath, markdown, 'utf-8');
    return reportPath;
  }
}
